"""v3.18.0 (2026-06-04) — Pre-open session plan store (FB-003 follow-up).

WHY
---
`shared/pre_open_behavior.py` (v3.15.0) is a pure interpretation layer; it
needs a place to PERSIST the per-symbol analysis so that monitors can later
read the plan during the trading day and feed it as an extra confidence
penalty/booster.

The plan is generated by `scripts/pre_open_session_planner.py` ~30 min
before market open. Monitors read it during the session via `get_plan()` and
`get_plan_for_symbol()`.

CONTRACT
--------
- Storage:    learning-loop/runtime_state.json::pre_open_plan
- Read API:   get_plan() → dict
              get_plan_for_symbol(symbol) → dict | None
- Write API:  store_plan(plan_date_iso, per_symbol_plan)
              clear_plan() — test helper, not for prod use

A "plan entry" per symbol shape:
    {
      "symbol":               str,
      "label":                str,           # e.g. GAP_UP_STRONG_PRE_OPEN
      "gap_pct":              float | None,
      "warnings":             [str, ...],    # e.g. ["pre_market_gap_strong"]
      "confidence_adjustment":float,         # capped to [-0.10, +0.05]
      "source":               str,           # "yahoo" / "nasdaq" / "unavailable"
      "rationale":            str,
      "generated_at":         iso8601,
    }

SAFETY
------
- Pure storage layer — never places trades.
- Caller (pre_open_session_planner) is the only writer.
- Monitors only READ (no permission needed).
- `confidence_adjustment` ALWAYS clamped to [-0.10, +0.05] regardless of
  what analyzer returned — defense-in-depth.
"""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Any

# Maximum positive boost allowed from this layer. Per contract this layer
# CANNOT raise confidence by more than +0.05 — that ceiling is enforced here
# regardless of upstream analyzer output (defense-in-depth).
MAX_POSITIVE_ADJUSTMENT = 0.05
MIN_NEGATIVE_ADJUSTMENT = -0.10


def _now_iso() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _clamp_adj(value: Any) -> float:
    """Clamp confidence_adjustment to [MIN_NEGATIVE_ADJUSTMENT, MAX_POSITIVE_ADJUSTMENT]."""
    try:
        v = float(value)
    except (TypeError, ValueError):
        return 0.0
    if v > MAX_POSITIVE_ADJUSTMENT:
        return MAX_POSITIVE_ADJUSTMENT
    if v < MIN_NEGATIVE_ADJUSTMENT:
        return MIN_NEGATIVE_ADJUSTMENT
    return v


def _sanitize_entry(symbol: str, entry: dict) -> dict:
    """Conservative normalization of one plan entry."""
    if not isinstance(entry, dict):
        return {
            "symbol":                symbol,
            "label":                 "INSUFFICIENT_DATA",
            "gap_pct":               None,
            "warnings":              ["malformed_entry"],
            "confidence_adjustment": 0.0,
            "source":                "unavailable",
            "rationale":             "non_dict_entry_clamped",
            "generated_at":          _now_iso(),
        }
    warnings = entry.get("warnings") or []
    if not isinstance(warnings, list):
        warnings = [str(warnings)]
    warnings = [str(w) for w in warnings if w]

    return {
        "symbol":                str(entry.get("symbol") or symbol),
        "label":                 str(entry.get("label") or "INSUFFICIENT_DATA"),
        "gap_pct":               entry.get("gap_pct"),
        "warnings":              warnings,
        "confidence_adjustment": _clamp_adj(entry.get("confidence_adjustment", 0.0)),
        "source":                str(entry.get("source") or "unavailable"),
        "rationale":             str(entry.get("rationale") or ""),
        "generated_at":          str(entry.get("generated_at") or _now_iso()),
    }


# ─── Public read API ─────────────────────────────────────────────────────────

def get_plan() -> dict:
    """Return the full pre_open_plan section. Empty dict if absent/corrupt."""
    try:
        try:
            from runtime_state import read_section
        except ImportError:
            from shared.runtime_state import read_section  # type: ignore
        plan = read_section("pre_open_plan")
        return plan if isinstance(plan, dict) else {}
    except Exception:
        return {}


def get_plan_for_symbol(symbol: str | None) -> dict | None:
    """Return plan entry for one symbol, or None if unknown / empty.

    Fail-soft. Never raises.
    """
    if not symbol or not isinstance(symbol, str):
        return None
    plan = get_plan()
    per_symbol = plan.get("per_symbol") or {}
    if not isinstance(per_symbol, dict):
        return None
    entry = per_symbol.get(symbol)
    if not isinstance(entry, dict):
        return None
    return entry


# ─── Public write API ─────────────────────────────────────────────────────────

def store_plan(
    plan_date_iso: str,
    per_symbol_plan: dict[str, dict],
    *,
    actor: str = "pre-open-planner",
    overall_warnings: list[str] | None = None,
) -> dict:
    """Persist a new pre-open plan to runtime_state.

    Args:
        plan_date_iso: YYYY-MM-DD ISO date of the trading session being planned.
        per_symbol_plan: {symbol → entry dict}.
        actor: writer label for runtime_state.
        overall_warnings: session-level warnings (e.g. "yahoo_rate_limit").

    Returns the sanitized payload that was written. Fail-soft (returns
    empty dict on persistence failure).
    """
    if not isinstance(per_symbol_plan, dict):
        per_symbol_plan = {}
    sanitized: dict[str, dict] = {}
    for sym, entry in per_symbol_plan.items():
        if not isinstance(sym, str) or not sym:
            continue
        sanitized[sym] = _sanitize_entry(sym, entry)

    payload = {
        "plan_date":    str(plan_date_iso or _now_iso()[:10]),
        "generated_at": _now_iso(),
        "per_symbol":   sanitized,
        "warnings":     [str(w) for w in (overall_warnings or []) if w],
        "symbols_planned": len(sanitized),
    }

    try:
        try:
            from runtime_state import write_section
        except ImportError:
            from shared.runtime_state import write_section  # type: ignore
        write_section("pre_open_plan", payload, actor=actor)
    except Exception:
        # Fail-soft — return what we tried to write so caller can log.
        return payload

    return payload


def clear_plan() -> None:
    """Test helper. Writes an empty plan. NOT for production use."""
    try:
        try:
            from runtime_state import write_section
        except ImportError:
            from shared.runtime_state import write_section  # type: ignore
        write_section("pre_open_plan", {
            "plan_date":       "",
            "generated_at":    _now_iso(),
            "per_symbol":      {},
            "warnings":        [],
            "symbols_planned": 0,
        }, actor="pre-open-planner-test")
    except Exception:
        pass


__all__ = [
    "MAX_POSITIVE_ADJUSTMENT", "MIN_NEGATIVE_ADJUSTMENT",
    "get_plan", "get_plan_for_symbol",
    "store_plan", "clear_plan",
]
