#!/usr/bin/env python3
"""v3.24 (2026-06-15) — ETAP 9 — Monitor runtime diagnostics reporter.

Reads the last 7 days of JSONL diagnostic files from
``learning-loop/monitor_runtime_diag/<YYYY-MM-DD>.jsonl``, aggregates
counts per monitor + token, and writes:

  * ``docs/MONITOR_RUNTIME_DIAGNOSTICS.md`` — human-readable matrix
  * ``learning-loop/monitor_runtime_diag_status_latest.json`` — machine
    payload for downstream agents

HARD SAFETY
-----------
Pure local I/O. No network. No broker. No paid services. Read-only on
diag files; the reporter never mutates them.
"""

from __future__ import annotations

import json
import os
import sys
from collections import OrderedDict, defaultdict
from datetime import datetime, timedelta, timezone
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parent.parent
DIAG_DIR = REPO_ROOT / "learning-loop" / "monitor_runtime_diag"
DOCS_OUT = REPO_ROOT / "docs" / "MONITOR_RUNTIME_DIAGNOSTICS.md"
JSON_OUT = REPO_ROOT / "learning-loop" / "monitor_runtime_diag_status_latest.json"


KNOWN_MONITORS = (
    "crypto-monitor",
    "price-monitor",
    "options-monitor",
    "defense-monitor",
    "twitter-monitor",
    "reddit-monitor",
    "geo-monitor",
    "politician-monitor",
)


KNOWN_TOKENS = (
    "RAN",
    "INPUT_EMPTY",
    "NO_SIGNAL",
    "SIGNAL_DETECTED",
    "EMIT_ATTEMPTED",
    "EMIT_SUCCESS",
    "EMIT_FAILED",
)


def _iter_diag_files(days: int = 7) -> list[Path]:
    """Return up to ``days`` recent JSONL diag files (today + lookback)."""
    if not DIAG_DIR.exists():
        return []
    today = datetime.now(timezone.utc).date()
    candidates = []
    for d in range(days):
        day = today - timedelta(days=d)
        fp = DIAG_DIR / f"{day.isoformat()}.jsonl"
        if fp.exists():
            candidates.append(fp)
    return candidates


def _aggregate(files: list[Path]) -> dict:
    counts: dict = defaultdict(lambda: defaultdict(int))
    total_rows = 0
    earliest: str | None = None
    latest: str | None = None
    for fp in files:
        try:
            with open(fp, encoding="utf-8") as f:
                for line in f:
                    line = line.strip()
                    if not line:
                        continue
                    try:
                        rec = json.loads(line)
                    except Exception:
                        continue
                    monitor = str(rec.get("monitor") or "unknown")
                    token = str(rec.get("token") or "UNKNOWN")
                    counts[monitor][token] += 1
                    total_rows += 1
                    ts = rec.get("timestamp")
                    if isinstance(ts, str):
                        if earliest is None or ts < earliest:
                            earliest = ts
                        if latest is None or ts > latest:
                            latest = ts
        except Exception:
            # Diag files are append-only; partial reads are tolerated.
            continue

    # Materialise to plain dicts so json.dumps works cleanly.
    materialised = {
        m: {t: int(counts[m].get(t, 0)) for t in KNOWN_TOKENS + ("UNKNOWN",)}
        for m in sorted(counts.keys())
    }
    return {
        "files_scanned":   [str(p.relative_to(REPO_ROOT)) for p in files],
        "total_rows":      total_rows,
        "earliest_record": earliest,
        "latest_record":   latest,
        "per_monitor":     materialised,
    }


def _render_markdown(agg: dict) -> str:
    lines: list[str] = []
    lines.append("# Monitor Runtime Diagnostics")
    lines.append("")
    lines.append("**Source:** v3.24 runtime diagnostics — generated by "
                 "`scripts/build_monitor_runtime_diagnostics_report.py`.")
    lines.append("")
    lines.append(f"**Files scanned:** {len(agg.get('files_scanned') or [])}  ")
    lines.append(f"**Total diag rows:** {agg.get('total_rows', 0)}  ")
    lines.append(f"**Earliest record:** `{agg.get('earliest_record') or 'n/a'}`  ")
    lines.append(f"**Latest record:** `{agg.get('latest_record') or 'n/a'}`")
    lines.append("")
    lines.append("## Token counts per monitor (last 7 days)")
    lines.append("")
    header = "| Monitor | " + " | ".join(KNOWN_TOKENS) + " |"
    sep    = "|---" * (len(KNOWN_TOKENS) + 1) + "|"
    lines.append(header)
    lines.append(sep)
    per = agg.get("per_monitor") or {}
    seen = list(per.keys())
    # Ensure all KNOWN_MONITORS appear even if absent in data.
    for m in KNOWN_MONITORS:
        if m not in seen:
            seen.append(m)
    for m in seen:
        row = per.get(m) or {t: 0 for t in KNOWN_TOKENS}
        cells = " | ".join(str(int(row.get(t, 0))) for t in KNOWN_TOKENS)
        lines.append(f"| `{m}` | {cells} |")
    lines.append("")
    lines.append("## Standing markers")
    lines.append("")
    lines.append("- HARD-SAFETY HELD: NO BROKER CALL, NO NETWORK CALL.")
    lines.append("- FREE OPERATION: zero paid services, zero LLM calls.")
    lines.append("- v3.24 builder version stamped on confidence rows.")
    lines.append("")
    lines.append(f"_Last generated: {datetime.now(timezone.utc).isoformat()}_")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    files = _iter_diag_files(days=7)
    agg = _aggregate(files)

    # Write JSON payload for downstream agents.
    JSON_OUT.parent.mkdir(parents=True, exist_ok=True)
    payload = OrderedDict([
        ("generated_at",   datetime.now(timezone.utc).isoformat()),
        ("builder_version", "v3.24.0"),
        ("hard_safety", {
            "broker_call": False,
            "network_call": False,
            "paid_service": False,
        }),
        ("aggregate", agg),
    ])
    with open(JSON_OUT, "w", encoding="utf-8") as f:
        json.dump(payload, f, ensure_ascii=False, indent=2)

    # Write Markdown report.
    DOCS_OUT.parent.mkdir(parents=True, exist_ok=True)
    md = _render_markdown(agg)
    with open(DOCS_OUT, "w", encoding="utf-8") as f:
        f.write(md)

    print(f"Wrote {DOCS_OUT.relative_to(REPO_ROOT)} "
          f"({len(md.encode('utf-8'))} bytes)")
    print(f"Wrote {JSON_OUT.relative_to(REPO_ROOT)} "
          f"({JSON_OUT.stat().st_size} bytes)")
    print(f"Files scanned: {len(files)} | total rows: {agg.get('total_rows', 0)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
